# Image Normalization

In [1]:
import time

import matplotlib.pyplot as plt

import numpy as np

import pandas

import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torchvision.models as models

In [2]:
transform = transforms.Compose([
    transforms.Resize((258,320)),
    transforms.ToTensor()])
dataset = datasets.ImageFolder("../data/",transform=transform)
loader = torch.utils.data.DataLoader(dataset, shuffle=False, num_workers=4, batch_size=256)

In [4]:
count = 0
mean = 0
var = 0

for i, (imgs, targets) in enumerate(loader):
    n_2 = len(imgs)
    mean_2 = imgs.mean(dim=(0,2,3))
    var_2 = imgs.var(dim=(0,2,3))
    mean_c = (count*mean + n_2*mean_2)/(count+n_2)
    var_c = (count*(var+(mean-mean_c)**2)+n_2*(var_2+(mean_2-mean_c)**2))/(count+n_2)
    # Update variables for next round
    mean = mean_c
    var = var_c
    count += n_2
    # Give status update
    print(mean, var, count, i)

tensor([0.5414, 0.5087, 0.4716]) tensor([0.0582, 0.0645, 0.0674]) 256 0
tensor([0.5385, 0.5220, 0.4858]) tensor([0.0545, 0.0602, 0.0628]) 512 1
tensor([0.5376, 0.5133, 0.4786]) tensor([0.0561, 0.0631, 0.0655]) 768 2
tensor([0.5432, 0.5031, 0.4699]) tensor([0.0583, 0.0681, 0.0700]) 1024 3
tensor([0.5461, 0.5038, 0.4705]) tensor([0.0587, 0.0704, 0.0722]) 1280 4
tensor([0.5492, 0.5012, 0.4637]) tensor([0.0589, 0.0705, 0.0736]) 1536 5
tensor([0.5431, 0.5006, 0.4634]) tensor([0.0596, 0.0697, 0.0731]) 1792 6
tensor([0.5384, 0.5022, 0.4655]) tensor([0.0592, 0.0685, 0.0723]) 2048 7
tensor([0.5360, 0.5047, 0.4676]) tensor([0.0588, 0.0681, 0.0721]) 2304 8
tensor([0.5306, 0.5049, 0.4667]) tensor([0.0594, 0.0678, 0.0720]) 2560 9
tensor([0.5271, 0.5071, 0.4648]) tensor([0.0596, 0.0673, 0.0717]) 2816 10
tensor([0.5247, 0.5095, 0.4643]) tensor([0.0602, 0.0673, 0.0719]) 3072 11
tensor([0.5209, 0.5090, 0.4647]) tensor([0.0623, 0.0688, 0.0732]) 3328 12
tensor([0.5225, 0.5129, 0.4676]) tensor([0.0605, 0.

tensor([0.4953, 0.5117, 0.4443]) tensor([0.0562, 0.0575, 0.0636]) 28416 110
tensor([0.4954, 0.5119, 0.4448]) tensor([0.0561, 0.0574, 0.0636]) 28672 111
tensor([0.4958, 0.5123, 0.4454]) tensor([0.0560, 0.0574, 0.0636]) 28928 112
tensor([0.4960, 0.5126, 0.4459]) tensor([0.0559, 0.0573, 0.0635]) 29184 113
tensor([0.4962, 0.5130, 0.4465]) tensor([0.0559, 0.0572, 0.0635]) 29440 114
tensor([0.4965, 0.5134, 0.4470]) tensor([0.0558, 0.0572, 0.0634]) 29696 115
tensor([0.4967, 0.5137, 0.4476]) tensor([0.0557, 0.0571, 0.0634]) 29952 116
tensor([0.4969, 0.5140, 0.4481]) tensor([0.0556, 0.0570, 0.0633]) 30208 117
tensor([0.4971, 0.5143, 0.4485]) tensor([0.0555, 0.0569, 0.0633]) 30464 118
tensor([0.4973, 0.5145, 0.4488]) tensor([0.0554, 0.0568, 0.0632]) 30720 119
tensor([0.4974, 0.5147, 0.4490]) tensor([0.0553, 0.0567, 0.0632]) 30976 120
tensor([0.4976, 0.5149, 0.4492]) tensor([0.0552, 0.0566, 0.0631]) 31232 121
tensor([0.4977, 0.5151, 0.4494]) tensor([0.0551, 0.0566, 0.0631]) 31488 122
tensor([0.49

tensor([0.5028, 0.5170, 0.4515]) tensor([0.0565, 0.0568, 0.0650]) 56320 219
tensor([0.5027, 0.5168, 0.4513]) tensor([0.0566, 0.0568, 0.0651]) 56576 220
tensor([0.5024, 0.5165, 0.4509]) tensor([0.0568, 0.0570, 0.0652]) 56832 221
tensor([0.5025, 0.5164, 0.4508]) tensor([0.0568, 0.0571, 0.0653]) 57088 222
tensor([0.5027, 0.5162, 0.4506]) tensor([0.0569, 0.0571, 0.0654]) 57344 223
tensor([0.5031, 0.5160, 0.4504]) tensor([0.0569, 0.0572, 0.0655]) 57600 224
tensor([0.5034, 0.5160, 0.4504]) tensor([0.0569, 0.0572, 0.0656]) 57856 225
tensor([0.5037, 0.5158, 0.4502]) tensor([0.0570, 0.0573, 0.0657]) 58112 226
tensor([0.5040, 0.5158, 0.4501]) tensor([0.0570, 0.0573, 0.0658]) 58368 227
tensor([0.5043, 0.5158, 0.4501]) tensor([0.0570, 0.0574, 0.0659]) 58624 228
tensor([0.5043, 0.5156, 0.4500]) tensor([0.0571, 0.0575, 0.0660]) 58880 229
tensor([0.5043, 0.5155, 0.4500]) tensor([0.0571, 0.0575, 0.0660]) 59136 230
tensor([0.5040, 0.5153, 0.4498]) tensor([0.0571, 0.0575, 0.0659]) 59392 231
tensor([0.50

In [7]:
std = var.sqrt()
mean, var, std

(tensor([0.5032, 0.5149, 0.4498]),
 tensor([0.0571, 0.0575, 0.0658]),
 tensor([0.2390, 0.2399, 0.2564]))

In [8]:
transform = transforms.Compose([
    transforms.Resize((258,320)),
    transforms.ToTensor()])
dataset = datasets.ImageFolder("../data/",transform=transform)
loader = torch.utils.data.DataLoader(dataset, shuffle=False, num_workers=4, batch_size=1000)

In [9]:
count = 0
mean = 0
var = 0

for i, (imgs, targets) in enumerate(loader):
    n_2 = len(imgs)
    mean_2 = imgs.mean(dim=(0,2,3))
    var_2 = imgs.var(dim=(0,2,3))
    mean_c = (count*mean + n_2*mean_2)/(count+n_2)
    var_c = (count*(var+(mean-mean_c)**2)+n_2*(var_2+(mean_2-mean_c)**2))/(count+n_2)
    # Update variables for next round
    mean = mean_c
    var = var_c
    count += n_2
    # Give status update
    print(mean, var, count, i)

tensor([0.5423, 0.5022, 0.4690]) tensor([0.0583, 0.0677, 0.0697]) 1000 0
tensor([0.5391, 0.5016, 0.4649]) tensor([0.0593, 0.0687, 0.0725]) 2000 1
tensor([0.5262, 0.5100, 0.4643]) tensor([0.0593, 0.0667, 0.0713]) 3000 2
tensor([0.5167, 0.5095, 0.4652]) tensor([0.0636, 0.0686, 0.0727]) 4000 3
tensor([0.4994, 0.4989, 0.4527]) tensor([0.0652, 0.0683, 0.0709]) 5000 4
tensor([0.4944, 0.4985, 0.4513]) tensor([0.0645, 0.0671, 0.0690]) 6000 5
tensor([0.4958, 0.4960, 0.4492]) tensor([0.0652, 0.0679, 0.0698]) 7000 6
tensor([0.4993, 0.4948, 0.4477]) tensor([0.0655, 0.0682, 0.0705]) 8000 7
tensor([0.5000, 0.4980, 0.4490]) tensor([0.0652, 0.0679, 0.0704]) 9000 8
tensor([0.4984, 0.4970, 0.4492]) tensor([0.0667, 0.0692, 0.0717]) 10000 9
tensor([0.4992, 0.4961, 0.4488]) tensor([0.0667, 0.0694, 0.0719]) 11000 10
tensor([0.4978, 0.4966, 0.4475]) tensor([0.0671, 0.0694, 0.0722]) 12000 11
tensor([0.4982, 0.4992, 0.4467]) tensor([0.0671, 0.0690, 0.0722]) 13000 12
tensor([0.4970, 0.4996, 0.4430]) tensor([0.0

In [10]:
std = var.sqrt()
mean, var, std

(tensor([0.5032, 0.5149, 0.4498]),
 tensor([0.0571, 0.0575, 0.0658]),
 tensor([0.2390, 0.2399, 0.2564]))